#!/usr/bin/env bash
set -euo pipefail

# =========================
# realm-box.sh
# Realm / Sing-box 双引擎中转管理器
# =========================

APP_REALM="realm"
APP_SBOX="sing-box"

BIN_REALM="/usr/local/bin/realm"
BIN_SBOX="/usr/local/bin/sing-box"

ETC_DIR="/etc/realm"
CFG_REALM="$ETC_DIR/config.toml"
CFG_SBOX="$ETC_DIR/sbox.json"
EP_DB="$ETC_DIR/endpoints.db"
MODE_FILE="$ETC_DIR/mode"   # 内容：realm 或 sbox

SERVICE_REALM="/etc/systemd/system/realm.service"
SERVICE_SBOX="/etc/systemd/system/sing-box-relay.service"

SBOX_VERSION="1.8.6"

GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m'

say()  { echo -e "${GREEN}$*${NC}"; }
warn() { echo -e "${YELLOW}$*${NC}"; }
err()  { echo -e "${RED}$*${NC}" >&2; }

need_root() {
  if [ "${EUID:-$(id -u)}" -ne 0 ]; then
    err "请使用 root 运行：sudo $0"
    exit 1
  fi
}

cmd_exists() { command -v "$1" >/dev/null 2>&1; }

require_cmds() {
  missing=""
  for c in "$@"; do
    if ! cmd_exists "$c"; then
      missing="$missing $c"
    fi
  done
  if [ -n "$missing" ]; then
    err "缺少依赖命令：$missing"
    err "Debian/Ubuntu: apt-get update && apt-get install -y$missing"
    err "CentOS/RHEL: yum install -y$missing"
    exit 1
  fi
}

is_number() {
  case "$1" in
    ''|*[!0-9]*) return 1 ;;
    *) return 0 ;;
  esac
}

os_pretty() {
  if [ -r /etc/os-release ]; then
    . /etc/os-release
    echo "${PRETTY_NAME:-Linux}"
  else
    echo "Linux"
  fi
}

detect_arch_asset_realm() {
  arch="$(uname -m)"
  case "$arch" in
    x86_64|amd64) echo "realm-x86_64-unknown-linux-gnu.tar.gz" ;;
    aarch64|arm64) echo "realm-aarch64-unknown-linux-gnu.tar.gz" ;;
    *)
      err "Realm 未适配架构：$arch"
      err "请手动下载 realm 到 $BIN_REALM 并 chmod +x，然后再用本脚本管理。"
      return 1
      ;;
  esac
}

detect_arch_asset_sbox() {
  arch="$(uname -m)"
  case "$arch" in
    x86_64|amd64)   echo "linux-amd64" ;;
    aarch64|arm64)  echo "linux-arm64" ;;
    armv7l|armv7)   echo "linux-armv7" ;;
    armv6l|armv6)   echo "linux-armv6" ;;
    i386|i686)      echo "linux-386" ;;
    mips)           echo "linux-mips" ;;
    mipsle)         echo "linux-mipsle" ;;
    mips64)         echo "linux-mips64" ;;
    mips64le)       echo "linux-mips64le" ;;
    riscv64)        echo "linux-riscv64" ;;
    *)
      err "Sing-box 未适配架构：$arch"
      err "请手动下载 sing-box 到 $BIN_SBOX 并 chmod +x，然后再用本脚本管理。"
      return 1
      ;;
  esac
}

get_primary_ipv4() {
  ip="$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if ($i=="src") {print $(i+1); exit}}' || true)"
  if [ -n "${ip:-}" ]; then
    echo "$ip"
    return
  fi
  ip="$(ip -4 addr show scope global 2>/dev/null | awk '/inet /{print $2}' | cut -d/ -f1 | head -n1 || true)"
  echo "${ip:-N/A}"
}

get_primary_ipv6() {
  ip="$(ip -6 route get 2606:4700:4700::1111 2>/dev/null | awk '{for(i=1;i<=NF;i++) if ($i=="src") {print $(i+1); exit}}' || true)"
  if [ -n "${ip:-}" ]; then
    echo "$ip"
    return
  fi
  ip="$(ip -6 addr show scope global 2>/dev/null | awk '/inet6 /{print $2}' | cut -d/ -f1 | head -n1 || true)"
  echo "${ip:-N/A}"
}

ensure_dirs() {
  mkdir -p "$ETC_DIR"
  touch "$EP_DB"
  chmod 600 "$EP_DB"
  if [ ! -f "$MODE_FILE" ]; then
    echo "realm" >"$MODE_FILE"
  fi
}

load_mode() {
  ensure_dirs
  if [ -f "$MODE_FILE" ]; then
    MODE="$(tr -d ' \t\r\n' <"$MODE_FILE" 2>/dev/null || echo "realm")"
  else
    MODE="realm"
  fi
  case "$MODE" in
    realm|sbox) : ;;
    *) MODE="realm"; echo "realm" >"$MODE_FILE" ;;
  esac
}

save_mode() {
  echo "$MODE" >"$MODE_FILE"
}

svc_exists_realm() { systemctl list-unit-files | awk '{print $1}' | grep -qx "realm.service"; }
svc_exists_sbox()  { systemctl list-unit-files | awk '{print $1}' | grep -qx "sing-box-relay.service"; }

write_service_realm() {
  cat >"$SERVICE_REALM" <<EOF
[Unit]
Description=Realm Relay Service
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
WorkingDirectory=$ETC_DIR
ExecStart=$BIN_REALM -c $CFG_REALM
Restart=on-failure
RestartSec=2s
LimitNOFILE=1048576

[Install]
WantedBy=multi-user.target
EOF
}

write_service_sbox() {
  cat >"$SERVICE_SBOX" <<EOF
[Unit]
Description=Sing-box Stream Relay
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
WorkingDirectory=$ETC_DIR
ExecStart=$BIN_SBOX run -c $CFG_SBOX
Restart=on-failure
RestartSec=2s
LimitNOFILE=1048576

[Install]
WantedBy=multi-user.target
EOF
}

regen_config_realm() {
  ensure_dirs

  cat >"$CFG_REALM" <<'EOF'
# Auto-generated by realm-box.sh
# Do not edit manually unless you know what you're doing.

[log]
level = "info"

[network]
no_tcp = false
use_udp = true

EOF

  while IFS= read -r line || [ -n "${line:-}" ]; do
    case "$line" in
      ''|\#*) continue ;;
    esac

    lp="$(echo "$line" | awk '{print $1}')"
    rh="$(echo "$line" | awk '{print $2}')"
    rp="$(echo "$line" | awk '{print $3}')"

    if [ -z "$lp" ] || [ -z "$rh" ] || [ -z "$rp" ]; then
      warn "跳过无效行：$line"
      continue
    fi
    if ! is_number "$lp" || [ "$lp" -lt 1 ] || [ "$lp" -gt 65535 ]; then
      warn "跳过非法本地端口：$line"
      continue
    fi
    if ! is_number "$rp" || [ "$rp" -lt 1 ] || [ "$rp" -gt 65535 ]; then
      warn "跳过非法目标端口：$line"
      continue
    fi

    config_rh="$rh"
    case "$config_rh" in
      *:*)
        case "$config_rh" in
          

\[*\]

) : ;;          # 已经有 []
          

\[*\:*] ) : ;;       # 宽松一点
          

\[* ) : ;;
          *\]

 ) : ;;
          *)
            config_rh="[$config_rh]"
            ;;
        esac
        ;;
    esac

    cat >>"$CFG_REALM" <<EOF
[[endpoints]]
listen = "[::]:${lp}"
remote = "${config_rh}:${rp}"

EOF
  done <"$EP_DB"

  if ! grep -q '^

\[

\[endpoints\]

\]

' "$CFG_REALM" 2>/dev/null; then
    cat >>"$CFG_REALM" <<'EOF'
# No endpoints configured yet.
# Use realm-box.sh -> 配置管理 -> 添加转发
EOF
  fi
}

regen_config_sbox() {
  ensure_dirs

  cat >"$CFG_SBOX" <<EOF
{
  "log": { "level": "info" },
  "inbounds": [
EOF

  first_in=1
  while IFS= read -r line || [ -n "${line:-}" ]; do
    case "$line" in
      ''|\#*) continue ;;
    esac

    lp="$(echo "$line" | awk '{print $1}')"
    rh="$(echo "$line" | awk '{print $2}')"
    rp="$(echo "$line" | awk '{print $3}')"

    if [ -z "$lp" ] || [ -z "$rh" ] || [ -z "$rp" ]; then
      warn "跳过无效行（sbox inbound）：$line"
      continue
    fi
    if ! is_number "$lp" || [ "$lp" -lt 1 ] || [ "$lp" -gt 65535 ]; then
      warn "跳过非法本地端口（sbox inbound）：$line"
      continue
    fi
    if ! is_number "$rp" || [ "$rp" -lt 1 ] || [ "$rp" -gt 65535 ]; then
      warn "跳过非法目标端口（sbox inbound）：$line"
      continue
    fi

    tag_safe="to-${rh}-${rp}"
    # 简单清洗 tag
    tag_safe="$(echo "$tag_safe" | tr -c 'a-zA-Z0-9_.-' '_')"

    if [ "$first_in" -eq 0 ]; then
      echo "," >>"$CFG_SBOX"
    fi
    first_in=0

    cat >>"$CFG_SBOX" <<EOF
    {
      "type": "tcp",
      "listen": "::",
      "listen_port": $lp,
      "sniff": false,
      "proxy_protocol": false,
      "outbound": "$tag_safe"
    }
EOF
  done <"$EP_DB"

  cat >>"$CFG_SBOX" <<EOF
  ],
  "outbounds": [
EOF

  first_out=1
  while IFS= read -r line || [ -n "${line:-}" ]; do
    case "$line" in
      ''|\#*) continue ;;
    esac

    lp="$(echo "$line" | awk '{print $1}')"
    rh="$(echo "$line" | awk '{print $2}')"
    rp="$(echo "$line" | awk '{print $3}')"

    if [ -z "$lp" ] || [ -z "$rh" ] || [ -z "$rp" ]; then
      continue
    fi
    if ! is_number "$rp" || [ "$rp" -lt 1 ] || [ "$rp" -gt 65535 ]; then
      continue
    fi

    tag_safe="to-${rh}-${rp}"
    tag_safe="$(echo "$tag_safe" | tr -c 'a-zA-Z0-9_.-' '_')"

    if [ "$first_out" -eq 0 ]; then
      echo "," >>"$CFG_SBOX"
    fi
    first_out=0

    cat >>"$CFG_SBOX" <<EOF
    {
      "type": "direct",
      "tag": "$tag_safe",
      "override_address": "$rh",
      "override_port": $rp
    }
EOF
  done <"$EP_DB"

  cat >>"$CFG_SBOX" <<EOF
  ]
}
EOF
}

install_realm() {
  need_root
  require_cmds curl tar systemctl ip awk grep sed uname head cut

  ensure_dirs

  asset="$(detect_arch_asset_realm)"

  tag="$(curl -fsSL "https://api.github.com/repos/zhboner/realm/releases/latest" \
    | sed -n 's/.*"tag_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' \
    | head -n1 || true)"

  if [ -z "${tag:-}" ]; then
    err "获取最新 Realm 版本失败（GitHub API）。"
    err "请检查网络，或手动下载 realm 到 $BIN_REALM。"
    exit 1
  fi

  url="https://github.com/zhboner/realm/releases/download/${tag}/${asset}"
  say "安装 Realm：${tag}（${asset}）"
  say "下载：${url}"

  tmp="$(mktemp -d)"
  trap 'rm -rf "$tmp"' EXIT

  curl -fL "$url" -o "$tmp/realm.tar.gz"
  tar -xzf "$tmp/realm.tar.gz" -C "$tmp"

  if [ ! -f "$tmp/realm" ]; then
    err "解压后未找到 realm 二进制。"
    exit 1
  fi

  install -m 0755 "$tmp/realm" "$BIN_REALM"

  regen_config_realm
  write_service_realm
  systemctl daemon-reload
  systemctl enable --now realm.service

  say "Realm 安装完成。"
  show_status
}

install_sbox() {
  need_root
  require_cmds curl tar systemctl uname

  ensure_dirs

  if [ -x "$BIN_SBOX" ]; then
    say "检测到已存在 sing-box：$BIN_SBOX，将直接配置服务与中转。"
  else
    arch_name="$(detect_arch_asset_sbox)"
    asset="sing-box-${SBOX_VERSION}-${arch_name}.tar.gz"
    url="https://cdn.jsdelivr.net/gh/SagerNet/sing-box@v${SBOX_VERSION}/release/${asset}"

    say "安装 Sing-box v${SBOX_VERSION}（${arch_name}）"
    say "下载：${url}"

    tmp="$(mktemp -d)"
    trap 'rm -rf "$tmp"' EXIT

    curl -fL "$url" -o "$tmp/sing-box.tar.gz"
    tar -xzf "$tmp/sing-box.tar.gz" -C "$tmp"

    sbox_bin="$(find "$tmp" -maxdepth 3 -type f -name 'sing-box' | head -n1 || true)"
    if [ -z "$sbox_bin" ]; then
      err "解压后未找到 sing-box 二进制。"
      exit 1
    fi

    install -m 0755 "$sbox_bin" "$BIN_SBOX"
    say "Sing-box 已安装到：$BIN_SBOX"
  fi

  regen_config_sbox
  write_service_sbox
  systemctl daemon-reload
  systemctl enable --now sing-box-relay.service

  say "Sing-box Relay 配置完成并已启动。"
  show_status
}

uninstall_realm() {
  need_root
  require_cmds systemctl

  if svc_exists_realm; then
    systemctl disable --now realm.service || true
  fi

  rm -f "$SERVICE_REALM"
  systemctl daemon-reload || true
  rm -f "$BIN_REALM"

  say "已卸载 Realm（保留配置目录：$ETC_DIR）"
}

uninstall_sbox() {
  need_root
  require_cmds systemctl

  if svc_exists_sbox; then
    systemctl disable --now sing-box-relay.service || true
  fi

  rm -f "$SERVICE_SBOX"
  systemctl daemon-reload || true
  # 不删除 BIN_SBOX，避免误删手动安装
  say "已卸载 Sing-box Relay 服务（保留二进制和配置目录：$ETC_DIR）"
}

add_endpoint() {
  need_root
  ensure_dirs

  echo
  printf "请输入本地监听端口（中转端口）： "
  read -r lp
  printf "请输入落地节点地址（IP 或域名）： "
  read -r rh
  printf "请输入落地节点端口： "
  read -r rp

  lp="${lp// /}"
  rh="${rh// /}"
  rp="${rp// /}"

  if [ -z "$lp" ] || [ -z "$rh" ] || [ -z "$rp" ]; then
    err "输入不能为空。"
    return 1
  fi
  if ! is_number "$lp" || [ "$lp" -lt 1 ] || [ "$lp" -gt 65535 ]; then
    err "本地端口非法：$lp"
    return 1
  fi
  if ! is_number "$rp" || [ "$rp" -lt 1 ] || [ "$rp" -gt 65535 ]; then
    err "目标端口非法：$rp"
    return 1
  fi

  if awk '{print $1}' "$EP_DB" | grep -qx "$lp"; then
    err "本地端口 $lp 已存在。请用“修改/删除”功能。"
    return 1
  fi

  echo "$lp $rh $rp" >>"$EP_DB"
  regen_config_realm
  regen_config_sbox
  say "已添加：[::]:${lp} -> ${rh}:${rp}"

  restart_service || true
}

list_endpoints() {
  ensure_dirs
  echo
  echo "当前转发列表（格式：本地端口  目标地址  目标端口）："
  if [ ! -s "$EP_DB" ]; then
    echo "(空)"
    return 0
  fi
  nl -ba "$EP_DB" | sed 's/^/  /'
}

delete_endpoint() {
  need_root
  ensure_dirs
  list_endpoints
  if [ ! -s "$EP_DB" ]; then
    return 0
  fi

  echo
  printf "请输入要删除的序号： "
  read -r n
  n="${n// /}"
  if ! is_number "$n" || [ "$n" -lt 1 ]; then
    err "序号非法：$n"
    return 1
  fi

  tmp="$(mktemp)"
  awk -v n="$n" 'NR!=n' "$EP_DB" >"$tmp"
  if cmp -s "$EP_DB" "$tmp"; then
    rm -f "$tmp"
    err "未删除任何行（可能序号不存在）。"
    return 1
  fi

  cat "$tmp" >"$EP_DB"
  rm -f "$tmp"

  regen_config_realm
  regen_config_sbox
  say "已删除序号：$n"
  restart_service || true
}

edit_endpoint() {
  need_root
  ensure_dirs
  list_endpoints
  if [ ! -s "$EP_DB" ]; then
    return 0
  fi

  echo
  printf "请输入要修改的序号： "
  read -r n
  n="${n// /}"
  if ! is_number "$n" || [ "$n" -lt 1 ]; then
    err "序号非法：$n"
    return 1
  fi

  old="$(awk -v n="$n" 'NR==n{print; exit}' "$EP_DB" || true)"
  if [ -z "$old" ]; then
    err "序号不存在：$n"
    return 1
  fi

  lp="$(echo "$old" | awk '{print $1}')"
  rh="$(echo "$old" | awk '{print $2}')"
  rp="$(echo "$old" | awk '{print $3}')"

  echo "当前：$old"
  printf "新的本地端口（回车保留 %s）： " "$lp"
  read -r nlp
  printf "新的目标地址（回车保留 %s）： " "$rh"
  read -r nrh
  printf "新的目标端口（回车保留 %s）： " "$rp"
  read -r nrp

  nlp="${nlp// /}"
  nrh="${nrh// /}"
  nrp="${nrp// /}"

  [ -z "$nlp" ] && nlp="$lp"
  [ -z "$nrh" ] && nrh="$rh"
  [ -z "$nrp" ] && nrp="$rp"

  if ! is_number "$nlp" || [ "$nlp" -lt 1 ] || [ "$nlp" -gt 65535 ]; then
    err "本地端口非法：$nlp"
    return 1
  fi
  if ! is_number "$nrp" || [ "$nrp" -lt 1 ] || [ "$nrp" -gt 65535 ]; then
    err "目标端口非法：$nrp"
    return 1
  fi

  if [ "$nlp" != "$lp" ]; then
    if awk -v n="$n" 'NR!=n{print $1}' "$EP_DB" | grep -qx "$nlp"; then
      err "本地端口 $nlp 已被其他规则使用。"
      return 1
    fi
  fi

  tmp="$(mktemp)"
  awk -v n="$n" -v lp="$nlp" -v rh="$nrh" -v rp="$nrp" 'BEGIN{OFS=" "} NR==n{$1=lp;$2=rh;$3=rp} {print}' "$EP_DB" >"$tmp"
  cat "$tmp" >"$EP_DB"
  rm -f "$tmp"

  regen_config_realm
  regen_config_sbox
  say "已修改：${nlp} ${nrh} ${nrp}"
  restart_service || true
}

restart_service() {
  need_root
  load_mode
  if [ "$MODE" = "realm" ]; then
    if svc_exists_realm; then
      systemctl restart realm.service
    else
      warn "realm.service 未安装"
    fi
  else
    if svc_exists_sbox; then
      systemctl restart sing-box-relay.service
    else
      warn "sing-box-relay.service 未安装"
    fi
  fi
  show_status
}

stop_service() {
  need_root
  load_mode
  if [ "$MODE" = "realm" ]; then
    if svc_exists_realm; then
      systemctl stop realm.service
    else
      warn "realm.service 未安装"
    fi
  else
    if svc_exists_sbox; then
      systemctl stop sing-box-relay.service
    else
      warn "sing-box-relay.service 未安装"
    fi
  fi
  show_status
}

start_service() {
  need_root
  load_mode
  if [ "$MODE" = "realm" ]; then
    if svc_exists_realm; then
      systemctl start realm.service
    else
      warn "realm.service 未安装"
    fi
  else
    if svc_exists_sbox; then
      systemctl start sing-box-relay.service
    else
      warn "sing-box-relay.service 未安装"
    fi
  fi
  show_status
}

show_logs() {
  require_cmds journalctl
  load_mode
  echo
  echo "按 Ctrl+C 退出日志查看。"
  if [ "$MODE" = "realm" ]; then
    journalctl -u realm.service -f --no-hostname -o cat
  else
    journalctl -u sing-box-relay.service -f --no-hostname -o cat
  fi
}

show_status() {
  require_cmds systemctl ip uname hostname awk

  load_mode

  v4="$(get_primary_ipv4)"
  v6="$(get_primary_ipv6)"

  echo
  echo "==================== 状态 ===================="
  echo "系统：$(os_pretty)"
  echo "主机：$(hostname)"
  echo "内核：$(uname -r)"
  echo "出口 IPv4：$v4"
  echo "出口 IPv6：$v6"
  echo "当前模式：$MODE"
  echo
  echo "Realm 二进制：$BIN_REALM $( [ -x "$BIN_REALM" ] && echo "(ok)" || echo "(missing)" )"
  echo "Realm 配置：$CFG_REALM $( [ -f "$CFG_REALM" ] && echo "(ok)" || echo "(missing)" )"
  echo "Realm 服务：realm.service"
  if svc_exists_realm; then
    systemctl --no-pager -l status realm.service || true
  else
    echo "realm.service 未安装"
  fi

  echo
  echo "Sing-box 二进制：$BIN_SBOX $( [ -x "$BIN_SBOX" ] && echo "(ok)" || echo "(missing)" )"
  echo "Sing-box 配置：$CFG_SBOX $( [ -f "$CFG_SBOX" ] && echo "(ok)" || echo "(missing)" )"
  echo "Sing-box 服务：sing-box-relay.service"
  if svc_exists_sbox; then
    systemctl --no-pager -l status sing-box-relay.service || true
  else
    echo "sing-box-relay.service 未安装"
  fi

  echo
  echo "==================== 转发规则 ===================="
  if [ -s "$EP_DB" ]; then
    nl -ba "$EP_DB" | sed 's/^/  /'
  else
    echo "  (空)"
  fi
  echo "=================================================="
}

tcp_connect_test() {
  host="$1"
  port="$2"
  timeout_s="${3:-3}"
  if cmd_exists timeout; then
    timeout "$timeout_s" bash -c "cat </dev/null >/dev/tcp/${host}/${port}" >/dev/null 2>&1 || return 1
  else
    bash -c "cat </dev/null >/dev/tcp/${host}/${port}" >/dev/null 2>&1 || return 1
  fi
}

link_test() {
  require_cmds ip getent awk sed head

  ensure_dirs
  if [ ! -s "$EP_DB" ]; then
    err "当前没有任何转发规则，无法测试。"
    return 1
  fi

  echo
  echo "将对每条规则进行："
  echo "1) 解析落地地址（如为域名）"
  echo "2) TCP 连通性探测（到 落地地址:落地端口）"
  echo "3) 本地端口占用情况提示"
  echo

  while IFS= read -r line || [ -n "${line:-}" ]; do
    case "$line" in
      ''|\#*) continue ;;
    esac

    lp="$(echo "$line" | awk '{print $1}')"
    rh="$(echo "$line" | awk '{print $2}')"
    rp="$(echo "$line" | awk '{print $3}')"

    echo "---- 规则：[::]:${lp} -> ${rh}:${rp}"

    resolved=""
    case "$rh" in
      *:*|*.*.*.*)  # 粗略判断 IP
        resolved="$rh"
        echo "解析：IP（无需解析）"
        ;;
      *)
        resolved="$(getent ahosts "$rh" 2>/dev/null | awk '{print $1}' | head -n1 || true)"
        if [ -n "$resolved" ]; then
          echo "解析：$rh -> $resolved"
        else
          echo "解析：失败（DNS/hosts）"
        fi
        ;;
    esac

    if cmd_exists ss; then
      if ss -ltn 2>/dev/null | awk '{print $4}' | grep -Eq "(^|:)$lp\$"; then
        echo "本地端口：$lp 已有 TCP 监听（可能冲突，也可能是 relay）"
      else
        echo "本地端口：$lp 未发现 TCP 监听"
      fi
    else
      echo "本地端口：未检测（缺少 ss 命令）"
    fi

    ok="FAIL"
    if [ -n "$resolved" ]; then
      if tcp_connect_test "$resolved" "$rp" 3; then
        ok="OK"
      fi
    fi
    echo "落地 TCP 探测：$ok"
    echo
  done <"$EP_DB"
}

config_menu() {
  while :; do
    echo
    echo "========== 配置管理 =========="
    echo "1) 添加转发"
    echo "2) 查看转发列表"
    echo "3) 修改转发"
    echo "4) 删除转发"
    echo "5) 返回上级"
    printf "请选择 [1-5]: "
    read -r c
    case "${c:-}" in
      1) add_endpoint ;;
      2) list_endpoints ;;
      3) edit_endpoint ;;
      4) delete_endpoint ;;
      5) break ;;
      *) warn "无效选择" ;;
    esac
  done
}

switch_mode() {
  need_root
  load_mode
  echo
  echo "当前模式：$MODE"
  echo "1) 切换为 Realm 模式"
  echo "2) 切换为 Sing-box 模式"
  printf "请选择 [1-2]: "
  read -r c
  case "${c:-}" in
    1)
      MODE="realm"
      save_mode
      say "已切换为 Realm 模式，请重启服务。"
      ;;
    2)
      MODE="sbox"
      save_mode
      say "已切换为 Sing-box 模式，请重启服务。"
      ;;
    *)
      warn "未更改模式。"
      ;;
  esac
}

main_menu() {
  need_root
  require_cmds systemctl ip awk sed grep
  load_mode

  while :; do
    echo
    echo "============== Realm / Sing-box 一键管理 =============="
    echo "当前模式：$MODE"
    echo "1) 安装 Realm"
    echo "2) 安装 Sing-box Relay（自动下载 v${SBOX_VERSION} 或使用已有二进制）"
    echo "3) 配置管理（添加/修改/删除转发）"
    echo "4) 启动服务（当前模式）"
    echo "5) 停止服务（当前模式）"
    echo "6) 重启服务（当前模式）"
    echo "7) 查看状态与信息"
    echo "8) 查看日志（实时，当前模式）"
    echo "9) 中转网络链路测试"
    echo "10) 切换模式（Realm / Sing-box）"
    echo "11) 卸载 Realm"
    echo "12) 卸载 Sing-box Relay"
    echo "0) 退出"
    printf "请选择 [0-12]: "
    read -r n

    case "${n:-}" in
      1) install_realm ;;
      2) install_sbox ;;
      3) config_menu ;;
      4) start_service ;;
      5) stop_service ;;
      6) restart_service ;;
      7) show_status ;;
      8) show_logs ;;
      9) link_test ;;
      10) switch_mode ;;
      11) uninstall_realm ;;
      12) uninstall_sbox ;;
      0) exit 0 ;;
      *) warn "无效选择" ;;
    esac
  done
}

main_menu
