#!/usr/bin/env bash
set -euo pipefail

# ==============
# Realm Manager
# ==============
APP="realm"
BIN="/usr/local/bin/realm"
ETC_DIR="/etc/realm"
CFG="$ETC_DIR/config.toml"
EP_DB="$ETC_DIR/endpoints.db"
SERVICE="/etc/systemd/system/realm.service"

GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m'

say()  { echo -e "${GREEN}$*${NC}"; }
warn() { echo -e "${YELLOW}$*${NC}"; }
err()  { echo -e "${RED}$*${NC}" >&2; }

need_root() {
  if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
    err "请使用 root 运行：sudo $0"
    exit 1
  fi
}

cmd_exists() { command -v "$1" >/dev/null 2>&1; }

require_cmds() {
  local missing=()
  for c in "$@"; do
    cmd_exists "$c" || missing+=("$c")
  done
  if ((${#missing[@]})); then
    err "缺少依赖命令：${missing[*]}"
    err "请先安装（Debian/Ubuntu）：apt-get update && apt-get install -y ${missing[*]}"
    err "请先安装（CentOS/RHEL）：yum install -y ${missing[*]}"
    exit 1
  fi
}

os_pretty() {
  if [[ -r /etc/os-release ]]; then
    . /etc/os-release
    echo "${PRETTY_NAME:-Linux}"
  else
    echo "Linux"
  fi
}

detect_arch_asset() {
  local arch
  arch="$(uname -m)"

  # 说明：
  # - 这里优先选用 GNU 构建的常见发行版包名（realm-ARCH-unknown-linux-gnu.tar.gz）
  # - 若你是 Alpine（musl），可能需要改为 musl 包（如果 release 提供）
  case "$arch" in
    x86_64|amd64) echo "realm-x86_64-unknown-linux-gnu.tar.gz" ;;
    aarch64|arm64) echo "realm-aarch64-unknown-linux-gnu.tar.gz" ;;
    *)
      err "不支持或未适配的架构：$arch"
      err "你可以手动下载 realm 并放到：$BIN（chmod +x），然后用本脚本进行配置/管理"
      return 1
      ;;
  esac
}

get_primary_ipv4() {
  # 优先用路由探测拿出口源 IP，失败则回退到第一个全局 IPv4
  local ip=""
  ip="$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if ($i=="src") {print $(i+1); exit}}' || true)"
  if [[ -n "${ip:-}" ]]; then
    echo "$ip"
    return 0
  fi
  ip="$(ip -4 addr show scope global 2>/dev/null | awk '/inet /{print $2}' | cut -d/ -f1 | head -n1 || true)"
  echo "${ip:-N/A}"
}

get_primary_ipv6() {
  local ip=""
  ip="$(ip -6 route get 2606:4700:4700::1111 2>/dev/null | awk '{for(i=1;i<=NF;i++) if ($i=="src") {print $(i+1); exit}}' || true)"
  if [[ -n "${ip:-}" ]]; then
    echo "$ip"
    return 0
  fi
  ip="$(ip -6 addr show scope global 2>/dev/null | awk '/inet6 /{print $2}' | cut -d/ -f1 | head -n1 || true)"
  echo "${ip:-N/A}"
}

ensure_dirs() {
  mkdir -p "$ETC_DIR"
  touch "$EP_DB"
  chmod 600 "$EP_DB"
}

is_installed() {
  [[ -x "$BIN" ]] && [[ -f "$SERVICE" ]]
}

svc_exists() { systemctl list-unit-files | awk '{print $1}' | grep -qx "realm.service"; }

svc_active() { systemctl is-active --quiet realm.service; }

write_service() {
  cat >"$SERVICE" <<EOF
[Unit]
Description=Realm Relay Service
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
WorkingDirectory=$ETC_DIR
ExecStart=$BIN -c $CFG
Restart=on-failure
RestartSec=2s
LimitNOFILE=1048576

[Install]
WantedBy=multi-user.target
EOF
}

regen_config_from_db() {
  ensure_dirs

  cat >"$CFG" <<'EOF'
# Auto-generated by realm.sh
# Do not edit manually unless you know what you're doing.

[log]
level = "info"

[network]
no_tcp = false
use_udp = true

EOF

  local line listen_port remote_host remote_port
  while IFS= read -r line || [[ -n "${line:-}" ]]; do
    [[ -z "${line// /}" ]] && continue
    [[ "${line:0:1}" == "#" ]] && continue

    listen_port="$(awk '{print $1}' <<<"$line")"
    remote_host="$(awk '{print $2}' <<<"$line")"
    remote_port="$(awk '{print $3}' <<<"$line")"

    if [[ -z "${listen_port:-}" || -z "${remote_host:-}" || -z "${remote_port:-}" ]]; then
      warn "跳过无效行：$line"
      continue
    fi

    if ! [[ "$listen_port" =~ ^[0-9]+$ ]] || ((listen_port < 1 || listen_port > 65535)); then
      warn "跳过非法本地端口：$line"
      continue
    fi
    if ! [[ "$remote_port" =~ ^[0-9]+$ ]] || ((remote_port < 1 || remote_port > 65535)); then
      warn "跳过非法目标端口：$line"
      continue
    fi

    cat >>"$CFG" <<EOF
[[endpoints]]
listen = "0.0.0.0:${listen_port}"
remote = "${remote_host}:${remote_port}"

EOF
  done <"$EP_DB"

  # 如果没有任何 endpoints，给个提示注释，避免 realm 启动看起来“什么也没干”
  if ! grep -q '^

\[

\[endpoints\]

\]

' "$CFG"; then
    cat >>"$CFG" <<'EOF'
# No endpoints configured yet.
# Use realm.sh -> 配置管理 -> 添加转发
EOF
  fi
}

install_realm() {
  need_root
  require_cmds curl tar systemctl ip awk grep sed uname head cut

  ensure_dirs

  local asset tag url tmp
  asset="$(detect_arch_asset)"

  # GitHub API 获取最新 release tag（不要求 jq）
  tag="$(curl -fsSL "https://api.github.com/repos/zhboner/realm/releases/latest" \
    | sed -n 's/.*"tag_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' \
    | head -n1 || true)"

  if [[ -z "${tag:-}" ]]; then
    err "获取最新版本失败（GitHub API）。你可以："
    err "1) 检查网络 / DNS"
    err "2) 手动下载 realm 放到 $BIN，然后继续使用本脚本管理配置"
    exit 1
  fi

  url="https://github.com/zhboner/realm/releases/download/${tag}/${asset}"
  say "即将安装 Realm：${tag}（${asset}）"
  say "下载：${url}"

  tmp="$(mktemp -d)"
  trap 'rm -rf "$tmp"' EXIT

  curl -fL "$url" -o "$tmp/realm.tar.gz"
  tar -xzf "$tmp/realm.tar.gz" -C "$tmp"

  if [[ ! -f "$tmp/realm" ]]; then
    err "解压后未找到 realm 二进制：$tmp/realm"
    exit 1
  fi

  install -m 0755 "$tmp/realm" "$BIN"

  regen_config_from_db
  write_service
  systemctl daemon-reload
  systemctl enable --now realm.service

  say "安装完成。"
  show_status
}

uninstall_realm() {
  need_root
  require_cmds systemctl rm ip

  if svc_exists; then
    systemctl disable --now realm.service || true
  fi

  rm -f "$SERVICE"
  systemctl daemon-reload || true

  rm -f "$BIN"

  # 配置是否删除给你选择
  echo
  read -r -p "是否删除配置目录 $ETC_DIR ？（会删 endpoints 配置）[y/N]: " ans
  case "${ans:-N}" in
    y|Y)
      rm -rf "$ETC_DIR"
      say "已删除配置目录。"
      ;;
    *)
      say "保留配置目录：$ETC_DIR"
      ;;
  esac

  say "卸载完成。"
}

add_endpoint() {
  need_root
  ensure_dirs

  echo
  read -r -p "请输入本地监听端口（中转端口）： " lp
  read -r -p "请输入落地节点地址（IP 或域名）： " rh
  read -r -p "请输入落地节点端口： " rp

  lp="${lp// /}"
  rp="${rp// /}"
  rh="${rh// /}"

  if [[ -z "${lp:-}" || -z "${rh:-}" || -z "${rp:-}" ]]; then
    err "输入不能为空。"
    return 1
  fi
  if ! [[ "$lp" =~ ^[0-9]+$ ]] || ((lp < 1 || lp > 65535)); then
    err "本地端口非法：$lp"
    return 1
  fi
  if ! [[ "$rp" =~ ^[0-9]+$ ]] || ((rp < 1 || rp > 65535)); then
    err "目标端口非法：$rp"
    return 1
  fi

  # 防止重复 listen_port
  if awk '{print $1}' "$EP_DB" | grep -qx "$lp"; then
    err "本地端口 $lp 已存在。请用“修改/删除”功能。"
    return 1
  fi

  echo "${lp} ${rh} ${rp}" >>"$EP_DB"
  regen_config_from_db
  say "已添加：0.0.0.0:${lp} -> ${rh}:${rp}"

  systemctl restart realm.service || true
  show_status
}

list_endpoints() {
  ensure_dirs
  echo
  echo "当前转发列表（格式：本地端口  目标地址  目标端口）："
  if [[ ! -s "$EP_DB" ]]; then
    echo "(空)"
    return 0
  fi

  nl -ba "$EP_DB" | sed 's/^/  /'
}

delete_endpoint() {
  need_root
  ensure_dirs
  list_endpoints

  if [[ ! -s "$EP_DB" ]]; then
    return 0
  fi

  echo
  read -r -p "请输入要删除的序号： " n
  n="${n// /}"
  if ! [[ "$n" =~ ^[0-9]+$ ]] || ((n < 1)); then
    err "序号非法：$n"
    return 1
  fi

  local tmp
  tmp="$(mktemp)"
  trap 'rm -f "$tmp"' RETURN

  awk -v n="$n" 'NR!=n' "$EP_DB" >"$tmp"
  if cmp -s "$EP_DB" "$tmp"; then
    err "未删除任何行（可能序号不存在）。"
    return 1
  fi

  cat "$tmp" >"$EP_DB"
  regen_config_from_db
  say "已删除序号：$n"
  systemctl restart realm.service || true
  show_status
}

edit_endpoint() {
  need_root
  ensure_dirs
  list_endpoints

  if [[ ! -s "$EP_DB" ]]; then
    return 0
  fi

  echo
  read -r -p "请输入要修改的序号： " n
  n="${n// /}"
  if ! [[ "$n" =~ ^[0-9]+$ ]] || ((n < 1)); then
    err "序号非法：$n"
    return 1
  fi

  local old lp rh rp
  old="$(awk -v n="$n" 'NR==n{print; exit}' "$EP_DB" || true)"
  if [[ -z "${old:-}" ]]; then
    err "序号不存在：$n"
    return 1
  fi

  lp="$(awk '{print $1}' <<<"$old")"
  rh="$(awk '{print $2}' <<<"$old")"
  rp="$(awk '{print $3}' <<<"$old")"

  echo
  echo "当前：$old"
  read -r -p "新的本地端口（回车保留 $lp）： " nlp
  read -r -p "新的目标地址（回车保留 $rh）： " nrh
  read -r -p "新的目标端口（回车保留 $rp）： " nrp

  nlp="${nlp// /}"
  nrh="${nrh// /}"
  nrp="${nrp// /}"

  [[ -z "${nlp:-}" ]] && nlp="$lp"
  [[ -z "${nrh:-}" ]] && nrh="$rh"
  [[ -z "${nrp:-}" ]] && nrp="$rp"

  if ! [[ "$nlp" =~ ^[0-9]+$ ]] || ((nlp < 1 || nlp > 65535)); then
    err "本地端口非法：$nlp"
    return 1
  fi
  if ! [[ "$nrp" =~ ^[0-9]+$ ]] || ((nrp < 1 || nrp > 65535)); then
    err "目标端口非法：$nrp"
    return 1
  fi

  # 如果改了本地端口，检查是否与其他行冲突
  if [[ "$nlp" != "$lp" ]]; then
    if awk -v n="$n" 'NR!=n{print $1}' "$EP_DB" | grep -qx "$nlp"; then
      err "本地端口 $nlp 已被其他规则使用。"
      return 1
    fi
  fi

  local tmp
  tmp="$(mktemp)"
  trap 'rm -f "$tmp"' RETURN

  awk -v n="$n" -v lp="$nlp" -v rh="$nrh" -v rp="$nrp" 'BEGIN{OFS=" "} NR==n{$1=lp;$2=rh;$3=rp} {print}' "$EP_DB" >"$tmp"
  cat "$tmp" >"$EP_DB"

  regen_config_from_db
  say "已修改：${nlp} ${nrh} ${nrp}"
  systemctl restart realm.service || true
  show_status
}

restart_service() { need_root; systemctl restart realm.service; show_status; }
stop_service()    { need_root; systemctl stop realm.service; show_status; }
start_service()   { need_root; systemctl start realm.service; show_status; }

show_logs() {
  require_cmds journalctl
  echo
  echo "按 Ctrl+C 退出日志查看。"
  journalctl -u realm.service -f --no-hostname -o cat
}

show_status() {
  require_cmds systemctl ip uname hostname awk

  local v4 v6
  v4="$(get_primary_ipv4)"
  v6="$(get_primary_ipv6)"

  echo
  echo "==================== 状态 ===================="
  echo "系统：$(os_pretty)"
  echo "主机：$(hostname)"
  echo "内核：$(uname -r)"
  echo "出口 IPv4：$v4"
  echo "出口 IPv6：$v6"
  echo "二进制：$BIN $([[ -x "$BIN" ]] && echo "(ok)" || echo "(missing)")"
  echo "配置：$CFG $([[ -f "$CFG" ]] && echo "(ok)" || echo "(missing)")"
  echo "服务：realm.service"
  if svc_exists; then
    systemctl --no-pager -l status realm.service || true
  else
    echo "realm.service 未安装"
  fi

  echo
  echo "==================== 转发规则 ===================="
  if [[ -s "$EP_DB" ]]; then
    nl -ba "$EP_DB" | sed 's/^/  /'
  else
    echo "  (空)"
  fi
  echo "=================================================="
}

tcp_connect_test() {
  # 使用 bash /dev/tcp 做一个轻量 TCP 探测（不会发送业务数据）
  local host="$1" port="$2" timeout_s="${3:-3}"

  # timeout 可能不存在，尽量兼容
  if cmd_exists timeout; then
    timeout "${timeout_s}" bash -c "cat < /dev/null > /dev/tcp/${host}/${port}" >/dev/null 2>&1
  else
    bash -c "cat < /dev/null > /dev/tcp/${host}/${port}" >/dev/null 2>&1
  fi
}

link_test() {
  require_cmds ip getent awk sed head

  ensure_dirs
  if [[ ! -s "$EP_DB" ]]; then
    err "当前没有任何转发规则，无法测试。"
    return 1
  fi

  echo
  echo "将对每条规则进行："
  echo "1) 解析落地地址（如为域名）"
  echo "2) TCP 连通性探测（到 落地地址:落地端口）"
  echo "3) 本地端口占用情况提示"
  echo

  local line lp rh rp resolved ok
  while IFS= read -r line || [[ -n "${line:-}" ]]; do
    [[ -z "${line// /}" ]] && continue
    [[ "${line:0:1}" == "#" ]] && continue

    lp="$(awk '{print $1}' <<<"$line")"
    rh="$(awk '{print $2}' <<<"$line")"
    rp="$(awk '{print $3}' <<<"$line")"

    echo "---- 规则：0.0.0.0:${lp} -> ${rh}:${rp}"

    resolved=""
    if [[ "$rh" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] || [[ "$rh" =~ : ]]; then
      resolved="$rh"
      echo "解析：IP（无需解析）"
    else
      # getent ahosts 兼容性好
      resolved="$(getent ahosts "$rh" 2>/dev/null | awk '{print $1}' | head -n1 || true)"
      if [[ -n "${resolved:-}" ]]; then
        echo "解析：$rh -> $resolved"
      else
        echo "解析：失败（DNS/hosts）"
      fi
    fi

    # 本地端口监听提示（不强依赖 ss）
    if cmd_exists ss; then
      if ss -ltn 2>/dev/null | awk '{print $4}' | grep -Eq "(^|:)$lp$"; then
        echo "本地端口：$lp 已有 TCP 监听（可能冲突，也可能是 realm）"
      else
        echo "本地端口：$lp 未发现 TCP 监听（若服务运行中仍显示无监听，检查配置/权限）"
      fi
    else
      echo "本地端口：未检测（缺少 ss 命令）"
    fi

    ok="FAIL"
    if [[ -n "${resolved:-}" ]]; then
      if tcp_connect_test "$resolved" "$rp" 3; then
        ok="OK"
      fi
    fi
    echo "落地 TCP 探测：$ok"
    echo
  done <"$EP_DB"
}

config_menu() {
  while true; do
    echo
    echo "========== 配置管理 =========="
    echo "1) 添加转发"
    echo "2) 查看转发列表"
    echo "3) 修改转发"
    echo "4) 删除转发"
    echo "5) 返回上级"
    read -r -p "请选择 [1-5]: " c
    case "${c:-}" in
      1) add_endpoint ;;
      2) list_endpoints ;;
      3) edit_endpoint ;;
      4) delete_endpoint ;;
      5) break ;;
      *) warn "无效选择" ;;
    esac
  done
}

main_menu() {
  need_root
  require_cmds systemctl ip awk sed grep

  while true; do
    echo
    echo "============== Realm 一键管理 =============="
    echo "1) 安装 Realm"
    echo "2) 配置管理（添加/修改/删除转发）"
    echo "3) 启动服务"
    echo "4) 停止服务"
    echo "5) 重启服务"
    echo "6) 查看状态与信息"
    echo "7) 查看日志（实时）"
    echo "8) 中转网络链路测试"
    echo "9) 卸载 Realm"
    echo "0) 退出"
    read -r -p "请选择 [0-9]: " n

    case "${n:-}" in
      1) install_realm ;;
      2) config_menu ;;
      3) start_service ;;
      4) stop_service ;;
      5) restart_service ;;
      6) show_status ;;
      7) show_logs ;;
      8) link_test ;;
      9) uninstall_realm ;;
      0) exit 0 ;;
      *) warn "无效选择" ;;
    esac
  done
}

main_menu
