#!/bin/bash

# ============================================
# Ubuntu Xray VLESS+Reality+Vision 模板级配置脚本
# 版本: v3.0.0
# 更新日期: 2025-12-19
# 目标: 全面模板化，支持系统 & Xray & Clash 自动优化
# ============================================

SCRIPT_VERSION="v3.0.0"

set -e

# ============================
# 颜色定义
# ============================
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error(){ echo -e "${RED}[ERROR]${NC} $1"; }

echo -e "${BLUE}============================================${NC}"
echo -e "${BLUE}   Xray VLESS+Reality+Vision 模板脚本${NC}"
echo -e "${BLUE}   版本: ${SCRIPT_VERSION}${NC}"
echo -e "${BLUE}============================================${NC}"
echo ""

if [[ $EUID -ne 0 ]]; then
    log_error "请使用root权限运行脚本"
    exit 1
fi

# ============================
# 模板级全局参数
# ============================

# ===== 系统 TCP 核心优化 =====
TEMPLATE_TCP_QDISC="fq"
TEMPLATE_TCP_CC="bbr"
TEMPLATE_RMEM_MAX=67108864
TEMPLATE_WMEM_MAX=67108864
TEMPLATE_TCP_RMEM="4096 524288 67108864"
TEMPLATE_TCP_WMEM="4096 524288 67108864"
TEMPLATE_TCP_MTU_PROBING=1
TEMPLATE_TCP_SLOW_START_IDLE=0

# ===== Xray 拆包 / 流控策略 =====
TEMPLATE_XRAY_FLOW="xtls-rprx-vision"
TEMPLATE_XRAY_FINGERPRINT="firefox"
TEMPLATE_XRAY_TCP_FASTOPEN=true

# ===== Clash 客户端行为策略 =====
CLASH_ENABLE_MUX=true
CLASH_MUX_CONCURRENCY=8
CLASH_UDP_ENABLED=false

# ============================
# 检测现有配置
# ============================

CONFIG_FILE="/usr/local/etc/xray/config.json"
BACKUP_FILE="/root/xray_vless_links.txt"
USE_EXISTING=false

if [ -f "$CONFIG_FILE" ] && [ -f "$BACKUP_FILE" ]; then
    log_warn "检测到现有Xray配置"
    EXISTING_UUID=$(grep -oP '"id":\s*"\K[^"]+' "$CONFIG_FILE" | head -1)
    EXISTING_PRIVATE=$(grep -oP '"privateKey":\s*"\K[^"]+' "$CONFIG_FILE" | head -1)
    EXISTING_SHORT=$(grep -oP '"shortIds":\s*\[\s*"\K[^"]+' "$CONFIG_FILE" | head -1)
    echo "UUID: $EXISTING_UUID"
    echo "Private Key: ${EXISTING_PRIVATE:0:20}..."
    echo "Short ID: $EXISTING_SHORT"
    echo ""
    echo "请选择操作："
    echo "1) 保留现有配置"
    echo "2) 生成新配置"
    echo "3) 退出"
    read -p "请输入选项 [1/2/3]: " CONFIG_CHOICE
    case $CONFIG_CHOICE in
        1) USE_EXISTING=true ;;
        2)
            USE_EXISTING=false
            BACKUP_DIR="/root/xray_backups"
            mkdir -p "$BACKUP_DIR"
            TIMESTAMP=$(date +%Y%m%d_%H%M%S)
            cp "$CONFIG_FILE" "$BACKUP_DIR/config_${TIMESTAMP}.json"
            cp "$BACKUP_FILE" "$BACKUP_DIR/links_${TIMESTAMP}.txt" 2>/dev/null || true
            log_info "旧配置已备份"
            ;;
        3) exit 0 ;;
        *) log_error "无效选项"; exit 1 ;;
    esac
fi

# ============================
# 用户节点名称
# ============================
if [ "$USE_EXISTING" = false ]; then
    read -p "请输入节点名称（回车使用默认）: " NODE_NAME
    NODE_NAME=${NODE_NAME:-Xray-Reality-$(date +%Y%m%d)}
fi

# ============================
# 系统优化（仅新配置）
# ============================
if [ "$USE_EXISTING" = false ]; then
    log_info "更新系统软件包..."
    apt update && apt upgrade -y
    apt autoremove -y && apt autoclean -y
    apt install -y curl wget unzip jq qrencode

    log_info "清理日志与临时文件..."
    journalctl --vacuum-time=3d
    rm -rf /tmp/* /var/tmp/*

    log_info "配置2GB交换空间..."
    if [ -f /swapfile ]; then swapoff /swapfile; rm -f /swapfile; fi
    fallocate -l 2G /swapfile
    chmod 600 /swapfile
    mkswap /swapfile
    swapon /swapfile
    grep -q '/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab

    log_info "启用 BBR TCP 拥塞控制..."
    SYSCTL_FILE="/etc/sysctl.d/99-xray-template.conf"
    cat > $SYSCTL_FILE <<EOF
# Generated by deploy-xray.sh
net.core.default_qdisc = $TEMPLATE_TCP_QDISC
net.ipv4.tcp_congestion_control = $TEMPLATE_TCP_CC

net.core.rmem_max = $TEMPLATE_RMEM_MAX
net.core.wmem_max = $TEMPLATE_WMEM_MAX
net.ipv4.tcp_rmem = $TEMPLATE_TCP_RMEM
net.ipv4.tcp_wmem = $TEMPLATE_TCP_WMEM

net.ipv4.tcp_mtu_probing = $TEMPLATE_TCP_MTU_PROBING
net.ipv4.tcp_slow_start_after_idle = $TEMPLATE_TCP_SLOW_START_IDLE
EOF
    sysctl --system

    log_info "安装 Xray-core..."
    bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install
fi

# ============================
# 密钥生成 / 读取
# ============================
if [ "$USE_EXISTING" = true ]; then
    UUID=$(grep -oP '"id":\s*"\K[^"]+' "$CONFIG_FILE" | head -1)
    PRIVATE_KEY=$(grep -oP '"privateKey":\s*"\K[^"]+' "$CONFIG_FILE" | head -1)
    SHORT_ID=$(grep -oP '"shortIds":\s*\[\s*"\K[^"]+' "$CONFIG_FILE" | head -1)
    if [ -f "$BACKUP_FILE" ]; then
        PUBLIC_KEY=$(grep "^Public Key:" "$BACKUP_FILE" | awk '{print $3}')
    fi
else
    UUID=$(cat /proc/sys/kernel/random/uuid)
    KEY_OUTPUT=$(/usr/local/bin/xray x25519 2>&1)
    PRIVATE_KEY=$(echo "$KEY_OUTPUT" | grep "^PrivateKey:" | cut -d' ' -f2 | tr -d ' \n\r')
    PUBLIC_KEY=$(echo "$KEY_OUTPUT" | grep "^PublicKey:" | cut -d' ' -f2 | tr -d ' \n\r')
    SHORT_ID=$(openssl rand -hex 8)
fi

# ============================
# 服务器 IP
# ============================
IPV4=$(curl -s -4 ifconfig.me || curl -s -4 icanhazip.com || curl -s -4 api.ipify.org)
IPV6=$(curl -s -6 ifconfig.me 2>/dev/null || echo "")

# ============================
# 创建 Xray 配置文件
# ============================
if [ "$USE_EXISTING" = false ]; then
    cat > /usr/local/etc/xray/config.json <<EOF
{
  "log": { "loglevel": "warning" },
  "inbounds": [{
    "port": 443,
    "protocol": "vless",
    "settings": { "clients":[{"id":"$UUID","flow":"$TEMPLATE_XRAY_FLOW"}], "decryption":"none" },
    "streamSettings": {
      "network": "tcp",
      "security": "reality",
      "sockopt": { "tcpFastOpen": $TEMPLATE_XRAY_TCP_FASTOPEN, "tcpNoDelay": true },
      "realitySettings": {
        "show": false,
        "dest": "www.drymt.com:443",
        "serverNames": ["www.drymt.com"],
        "privateKey": "$PRIVATE_KEY",
        "shortIds": ["$SHORT_ID"]
      }
    },
    "sniffing": { "enabled": true, "destOverride": ["http","tls","quic"] }
  }],
  "outbounds":[{"protocol":"freedom","tag":"direct"},{"protocol":"blackhole","tag":"block"}],
  "routing":{"rules":[{"type":"field","protocol":["bittorrent"],"outboundTag":"block"}]}
}
EOF

    /usr/local/bin/xray run -test -config /usr/local/etc/xray/config.json

    log_info "启动 Xray 服务..."
    systemctl daemon-reload
    systemctl enable xray
    systemctl restart xray
fi

# ============================
# Clash 输出函数
# ============================
gen_clash_proxy() {
cat <<EOF
  - name: "$1"
    type: vless
    server: $2
    port: 443
    uuid: $UUID
    network: tcp
    tls: true
    udp: ${CLASH_UDP_ENABLED}
    flow: $TEMPLATE_XRAY_FLOW
    servername: www.drymt.com
    reality-opts:
      public-key: $PUBLIC_KEY
      short-id: $SHORT_ID
    client-fingerprint: $TEMPLATE_XRAY_FINGERPRINT
    mux:
      enabled: $CLASH_ENABLE_MUX
      concurrency: $CLASH_MUX_CONCURRENCY
EOF
}

echo "proxies:" > /root/clash_config.yaml
gen_clash_proxy "$NODE_NAME" "$IPV4" >> /root/clash_config.yaml
[ -n "$IPV6" ] && gen_clash_proxy "${NODE_NAME}-IPv6" "$IPV6" >> /root/clash_config.yaml

# ============================
# 输出节点信息 + 模板说明
# ============================
cat > /root/xray_vless_links.txt <<EOF
Xray VLESS+Reality+Vision 节点信息 (模板 v3.0.0)
========================================
节点名称: $NODE_NAME
UUID: $UUID
Private Key: $PRIVATE_KEY
Public Key: $PUBLIC_KEY
Short ID: $SHORT_ID
服务器IPv4: $IPV4
$([ -n "$IPV6" ] && echo "服务器IPv6: $IPV6")
端口: 443
流控: $TEMPLATE_XRAY_FLOW
TLS: Reality
SNI: www.drymt.com
Fingerprint: $TEMPLATE_XRAY_FINGERPRINT

模板策略:
- TCP: $TEMPLATE_TCP_CC + $TEMPLATE_TCP_QDISC
- Xray: Flow $TEMPLATE_XRAY_FLOW, TCP FastOpen $TEMPLATE_XRAY_TCP_FASTOPEN
- Clash: Mux $CLASH_ENABLE_MUX, UDP $CLASH_UDP_ENABLED
- 主要用途: 网站/视频访问

VLESS URI (IPv4):
vless://$UUID@$IPV4:443?encryption=none&flow=$TEMPLATE_XRAY_FLOW&security=reality&sni=www.drymt.com&fp=$TEMPLATE_XRAY_FINGERPRINT&pbk=$PUBLIC_KEY&sid=$SHORT_ID&type=tcp&headerType=none#$NODE_NAME

配置文件: /usr/local/etc/xray/config.json
Clash YAML: /root/clash_config.yaml
========================================
EOF

log_info "模板级节点配置完成 ✓"
